name: sba_gas_scale
description: "SBA Gas Scale Telemetry Dashboard & BLE Controller"
publish_to: 'none'
version: 1.2.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_blue_plus: ^1.32.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
